---
- name: Ensure EPEL is installed
  yum:
    name: epel-release
    state: present

- name: Ensure pip and dependancies are installed
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python-pip
    - python-devel

- name: Install Ansible pip packages
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - ansible
    - ansible-runner
    - ansible_cmdb

- name: Ensure Directories are created
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  with_items:
    - path: /var/log/runner
      mode: "0777"
    - path: /var/ansible/playbooks
      mode: "0755"
    - path: /var/ansible/runner
      mode: "0755"

- name: Create the runner python script
  copy:
    src: runner.py
    dest: /var/ansible/runner/runner.py
    mode: 0755

- name: Copy test playbook
  copy:
    src: "{{ item }}"
    dest: /var/ansible/playbooks/
  with_items:
    - facts.yml
    - cmdb.yml
    - diskclean.yml
